environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"

branches:
  except:
    - gh-pages
    - adding_icons

platform:
    - x64

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # - pip install coverage
  # - pip install codecov
  - cmd: cd C:\projects
  - cmd: cd C:\projects\uv-align-distribute
  - cmd: python utils\download_blender.py

build: off

test_script:
  - cmd: python tests.py ../blender/blender
