# source: https://anzui.de/en/blog/2015-05-21/#menu

# this is essential to make python work out of the box
language: python

os:
  - linux
# Define which python version to build against.

python:
  - "3.7.4"

# blocklist
branches:
  except:
  - adding_icons
  - gh-pages

before_install:
  # update apt-gets repository sources
  - sudo apt-get update -qq
  # install blender from official sources.
  # This will most propably install an outdated blender version,
  # but it will resolve all system dependencies blender has to be able to run.
  - sudo apt-get install blender
  - pip install poetry

install:
  # codecoverage
  # - pip install codecov
  - poetry install --no-root
  - sudo ls
  - .venv/Scripts/activate
  - sudo python utils/download_blender.py
# Finally start our test runner passing it the blender executable from the downloaded blender release
script:
  - python tests.py ./blender-linux/blender

# after_success:
#  - bash <(curl -s https://codecov.io/bash)
