# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: uv-align-distribute

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Blender
      run: |
        sudo apt-get install blender
        sudo apt-get update -qq
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.in-project true
        poetry install --no-root
        .venv/Scripts/activate

    - name: Download Blender
      run: |
        python utils/download_blender.py

    - name: Test with pytest
      run: |
        python tests.py ../blender-linux/blender
